export enum ActionTypes {
    //auth
    TRY_SIGNUP = 'TRY_SIGNUP',
    TRY_SIGNIN = 'TRY_SIGNIN',
    SIGNUP = 'SIGNUP',
    SIGNIN = 'SIGNIN',
    LOGOUT = 'LOGOUT',
    //shopping-list
    SET_TOKEN = 'SET_TOKEN',
    ADD_INGREDIENT = 'ADD_INGREDIENT',
    ADD_INGREDIENTS = 'ADD_INGREDIENTS',
    DELETE_INGREDIENT = 'DELETE_INGREDIENT',
    UPDATE_INGREDIENT = 'UPDATE_INGREDIENT',
    START_EDIT = 'START_EDIT',
    STOP_EDIT = 'STOP_EDIT',
    //recipes
    SET_RECIPES = 'SET_RECIPES',
    ADD_RECIPE = 'ADD_RECIPE',
    UPDATE_RECIPE = 'UPDATE_RECIPE',
    DELETE_RECIPE = 'DELETE_RECIPE',
    STORE_RECIPES = 'STORE_RECIPES',
    FETCH_RECIPES = 'FETCH_RECIPES'
}